#pragma once

enum graphicsVendor_t
{
    VENDOR_NVIDIA,
    VENDOR_AMD,
    VENDOR_INTEL,
};

enum frameAllocType_t
{
    FRAME_ALLOC_VIEW_DEF,
    FRAME_ALLOC_VIEW_ENTITY,
    FRAME_ALLOC_VIEW_LIGHT,
	FRAME_ALLOC_SURFACE_TRIANGLES,
	FRAME_ALLOC_DRAW_SURFACE,
	FRAME_ALLOC_INTERACTION_STATE,
	FRAME_ALLOC_SHADOW_ONLY_ENTITY,
	FRAME_ALLOC_SHADOW_VOLUME_PARMS,
	FRAME_ALLOC_SHADER_REGISTER,
	FRAME_ALLOC_DRAW_SURFACE_POINTER,
	FRAME_ALLOC_DRAW_COMMAND,
	FRAME_ALLOC_UNKNOWN,
	FRAME_ALLOC_MAX
};

const int SMALLCHAR_WIDTH = 8;
const int SMALLCHAR_HEIGHT = 16;
const int BIGCHAR_WIDTH = 16;
const int BIGCHAR_HEIGHT = 16;

const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 480;

const int TITLESAFE_LEFT = 32;
const int TITLESAFE_RIGHT = 608;
const int TITLESAFE_TOP = 24;
const int TITLESAFE_BOTTOM = 456;
const int TITLESAFE_WIDTH = TITLESAFE_RIGHT - TITLESAFE_LEFT;
const int TITLESAFE_HEIGHT = TITLESAFE_BOTTOM - TITLESAFE_TOP;

class idRenderSystem
{
public:
    virtual ~idRenderSystem() {}

    virtual void Init() = 0;
};

extern idRenderSystem * renderSystem;